# Generated by Django 2.2.3 on 2020-03-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='serial_no',
        ),
        migrations.RemoveField(
            model_name='device',
            name='terminal',
        ),
        migrations.AddField(
            model_name='client',
            name='serial_no',
            field=models.CharField(default='', max_length=50, verbose_name='شماره سریال'),
        ),
        migrations.AddField(
            model_name='client',
            name='terminal',
            field=models.CharField(default='', max_length=50, verbose_name='ترمینال'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.CharField(default='', max_length=20, verbose_name='تاریخ درخواست'),
        ),
        migrations.AlterField(
            model_name='client',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Device', verbose_name='دستگاه'),
        ),
        migrations.AlterField(
            model_name='client',
            name='melli_id',
            field=models.CharField(default='', max_length=20, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='client',
            name='paid',
            field=models.CharField(default=0, max_length=10, verbose_name='پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default='09', max_length=15, verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_stat',
            field=models.CharField(default='', max_length=20, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='client',
            name='shop',
            field=models.CharField(default='', max_length=50, verbose_name='فروشگاه'),
        ),
        migrations.AlterField(
            model_name='device',
            name='app',
            field=models.CharField(blank=True, max_length=50, verbose_name='اپ'),
        ),
        migrations.AlterField(
            model_name='device',
            name='count',
            field=models.IntegerField(default=1, verbose_name='تعداد'),
        ),
        migrations.AlterField(
            model_name='device',
            name='details',
            field=models.TextField(default='', verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='نام دستگاه'),
        ),
        migrations.AlterField(
            model_name='device',
            name='price',
            field=models.CharField(default=0, max_length=50, verbose_name='قیمت'),
        ),
    ]
