# Generated by Django 2.2.3 on 2020-03-13 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200312_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name_plural': 'دستگاه ها'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='paid',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='مبلغ')),
                ('date', models.CharField(default='', max_length=20, verbose_name='تاریخ پرداخت')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Client', verbose_name='مشتری')),
            ],
            options={
                'verbose_name_plural': 'پرداختی ها',
            },
        ),
    ]
