# Generated by Django 2.2.3 on 2020-03-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='detail',
            field=models.TextField(default='', verbose_name='توضیحات'),
        ),
    ]
